---
- hosts: all
  name: Install requirements to run playbook properly
  gather_facts: false
  pre_tasks:
   - raw: timedatectl  set-timezone Asia/Jerusalem && ntpdate ntp.ubuntu.com && apt update && apt install -y python-pip  && pip install docker-py
     ignore_unreachable: true
- hosts: docker_hosts
  ignore_unreachable: true
  roles:
          - { role: docker, when: " '{{ [docker] }}'  is subset(choices) "}
- hosts: dockerize_hosts
  ignore_unreachable: true
  roles:
          - { role: docker,    when:  " '{{ [dockerize] }}' or '{{ '[docker,dockerize]' }}' is subset(choices) " }
          - { role: dockerize, when: " 'dockerize' in choices " }
- hosts: elasticsearch_hosts
  ignore_unreachable: true
  roles:
          - { role: elasticsearch, when: " 'elasticsearch' in choices" }
- hosts: kibana_hosts
  ignore_unreachable: true
  roles:
          - { role: kibana, when: " 'kibana' in choices" }
- hosts: metricbeat_hosts
  ignore_unreachable: true
  roles:
          - { role: metricbeat, when: " 'metricbeat' in choices" }